name: EasyLoan Build APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Pre-build Configuration
        run: |
          mkdir -p android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
          cd android
          # Version 8.5 use karna hai (Compatibility ke liye)
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew

      - name: Build APK
        run: |
          # Agar gradlew generate ho gaya hai toh use use karke build karo
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EasyLoan-Final-APK
          path: build/app/outputs/flutter-apk/app-release.apk
